# app/Dockerfile

FROM python:3.9-slim

EXPOSE 5000

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    software-properties-common \
    ffmpeg \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip3 install -r requirements.txt
RUN pwd

ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]